import { z } from "zod";
import { deriveRejectedQuantity, validateReceivingQuantities } from "../qa/_receiving-evaluation";
import { receivingLotAllocationError, rejectedLotAllocationError } from "./_lot-allocation";

export const RECEIVING_COMMIT_CONTRACT_VERSION = "v1" as const;
export const RECEIVING_POSTING_ENABLED = true;

export function receiptNumberForLine(receiptNumber: string, lineId: number): string {
    const suffix = `-${lineId}`;
    return `${receiptNumber.slice(0, Math.max(1, 50 - suffix.length))}${suffix}`;
}

const quantity = z.number().finite().nonnegative();
const optionalDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable();
const acceptedLotAllocation = z.object({
    storageLotId: z.number().int().positive(),
    quantity
});
const rejectedLotAllocation = z.object({
    storageLotId: z.number().int().positive(),
    quantity
});

export const receivingCommitLineSchema = z.object({
    lineId: z.number().int().positive(),
    productId: z.number().int().positive(),
    receivedQuantity: quantity,
    acceptedQuantity: quantity,
    rejectedQuantity: quantity,
    storageLotId: z.number().int().positive().nullable(),
    acceptedLotAllocations: z.array(acceptedLotAllocation).default([]),
    rejectedLotAllocations: z.array(rejectedLotAllocation).default([]),
    supplierBatchNumber: z.string().max(50),
    manufacturingDate: optionalDate,
    expiryDate: optionalDate,
    remarks: z.string().max(255).nullable(),
    isPackaging: z.boolean(),
    readings: z.array(z.object({
        specId: z.number().int().positive(),
        actualReading: z.string().trim().min(1).max(100)
    }))
}).superRefine((line, context) => {
    const message = validateReceivingQuantities(line);
    if (message) context.addIssue({ code: z.ZodIssueCode.custom, path: ["receivedQuantity"], message });
    const allocationMessage = receivingLotAllocationError(
        line.acceptedQuantity,
        line.acceptedLotAllocations,
        line.storageLotId
    );
    if (allocationMessage) context.addIssue({ code: z.ZodIssueCode.custom, path: ["acceptedLotAllocations"], message: allocationMessage });
    const rejectedAllocationMessage = rejectedLotAllocationError(
        line.rejectedQuantity,
        line.rejectedLotAllocations,
        line.storageLotId
    );
    if (rejectedAllocationMessage) context.addIssue({ code: z.ZodIssueCode.custom, path: ["rejectedLotAllocations"], message: rejectedAllocationMessage });
}).transform(line => ({
    ...line,
    rejectedQuantity: deriveRejectedQuantity(line.receivedQuantity, line.acceptedQuantity)
}));

const serverOwnedNumber = z.string().trim().max(50).optional();

const receivingRequestSchema = z.object({
    shipmentId: z.number().int().positive(),
    replacementDispositionId: z.number().int().positive().nullable().optional(),
    receiptNumber: serverOwnedNumber,
    supplierDocumentNumber: serverOwnedNumber,
    referenceNumber: serverOwnedNumber,
    grnNumber: serverOwnedNumber,
    receiptMode: z.enum(["full", "partial"]).default("full"),
    processOverDelivery: z.boolean().default(false),
    destinationBranchId: z.number().int().positive(),
    lines: z.array(receivingCommitLineSchema).min(1)
});

function rejectClientOwnedNumbers(value: z.infer<typeof receivingRequestSchema>, context: z.RefinementCtx) {
    for (const field of ["receiptNumber", "supplierDocumentNumber", "referenceNumber", "grnNumber"] as const) {
        if (value[field]?.trim()) {
            context.addIssue({
                code: z.ZodIssueCode.custom,
                path: [field],
                message: "Receipt Number is autogenerated on commit and cannot be submitted."
            });
        }
    }
}

export const receivingPreviewRequestSchema = receivingRequestSchema.superRefine(rejectClientOwnedNumbers);
export const receivingCommitRequestSchema = receivingRequestSchema.extend({
    contractVersion: z.literal(RECEIVING_COMMIT_CONTRACT_VERSION),
    workflowRevision: z.number().int().nonnegative()
}).superRefine(rejectClientOwnedNumbers);

export interface FinalReceivingMovement {
    movementId: number;
    lineId: number;
    kind: "Passed" | "Rejected";
    receivingLineId: number;
    inventoryLotId: number;
    productId: number;
    storageLotId: number;
    branchId: number;
    transactionTypeId: number;
    sourceDocumentNo: string;
    quantity: number;
}

export interface FinalReceivingAllocation {
    allocationId: number;
    lineId: number;
    receivingLineId: number;
    purchaseOrderReceivingId: number;
    jobOrderId: number;
    jobOrderMaterialId: number;
    productId: number;
    quantity: number;
    inventoryLotIds: number[];
}

export interface FinalReceivingRecord {
    receivingRecordId: number;
    lineId: number;
    shipmentId: number;
    productId: number;
    receiptNumber: string;
    branchId: number;
    storageLotId: number;
    batchNumber: string;
    receivedQuantity: number;
    rejectedQuantity: number;
    isOverReceived: boolean;
    overDeliveryQuantity: number;
    unitPrice: number;
    finalLandedUnitCost: number;
    qaStatus: string;
    expirationDate: string | null;
    receivedDate: string | null;
    inventoryLotIds: number[];
    qaResultIds: number[];
    allocationIds: number[];
}

export interface ReceivingCommitResult {
    contractVersion: typeof RECEIVING_COMMIT_CONTRACT_VERSION;
    mode: "compatibility";
    commitReference: string;
    receivingTicketNumber: string;
    idempotentReplay: boolean;
    shipmentId: number;
    status: "Partially Received" | "Received" | "Rejected";
    paymentStatus: number | null;
    workflowRevision: number;
    receivingRecordIds: number[];
    inventoryLotIds: number[];
    allocationIds: number[];
    receiptNumbers: string[];
    receivingRecords: FinalReceivingRecord[];
    movements: FinalReceivingMovement[];
    allocations: FinalReceivingAllocation[];
}

export type ReceivingCommitRequest = z.infer<typeof receivingCommitRequestSchema>;
export type ReceivingPreviewRequest = z.infer<typeof receivingPreviewRequestSchema>;
