"use client";

import React from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Settings2, X, RotateCcw, Calendar } from "lucide-react";
import { SearchableSelect } from "@/modules/manufacturing-management/shared/components/SearchableSelect";
import { useMachineDepreciationOverhead, type DepreciationTab } from "./hooks/useMachineDepreciationOverhead";
import { OverviewTab } from "./components/OverviewTab";
import { MachineAnalysisTab } from "./components/MachineAnalysisTab";
import { JobOrderAllocationTab } from "./components/JobOrderAllocationTab";
import { DetailsTab } from "./components/DetailsTab";

const TABS: { id: DepreciationTab; label: string }[] = [
  { id: "overview", label: "Overview" },
  { id: "machines", label: "Machine Analysis" },
  { id: "job-orders", label: "Job Order Allocation" },
  { id: "details", label: "Details" },
];

function getPresetRange(preset: "this-month" | "last-month" | "ytd") {
  const now = new Date();
  const y = now.getFullYear();
  const m = now.getMonth();
  const pad = (n: number) => String(n).padStart(2, "0");
  const todayStr = `${y}-${pad(m + 1)}-${pad(now.getDate())}`;

  if (preset === "this-month") {
    return {
      dateFrom: `${y}-${pad(m + 1)}-01`,
      dateTo: todayStr,
    };
  }
  if (preset === "last-month") {
    const prevMonthLastDay = new Date(y, m, 0);
    const prevY = prevMonthLastDay.getFullYear();
    const prevM = prevMonthLastDay.getMonth() + 1;
    const prevDays = prevMonthLastDay.getDate();
    return {
      dateFrom: `${prevY}-${pad(prevM)}-01`,
      dateTo: `${prevY}-${pad(prevM)}-${pad(prevDays)}`,
    };
  }
  // YTD
  return {
    dateFrom: `${y}-01-01`,
    dateTo: todayStr,
  };
}

export default function MachineDepreciationOverheadModule() {
  const {
    filters,
    setFilters,
    pendingFilters,
    setPendingFilters,
    applyFilters,
    resetFilters,
    activeTab,
    setActiveTab,
    overviewData,
    overviewLoading,
    overviewError,
    refetchOverview,
    machinesData,
    machinesLoading,
    machinesError,
    refetchMachines,
    jobOrdersData,
    jobOrdersLoading,
    jobOrdersError,
    refetchJobOrders,
    detailsData,
    detailsLoading,
    detailsError,
    detailsPage,
    setDetailsPage,
    refetchDetails,
    filterOptions,
    filterOptionsLoading,
  } = useMachineDepreciationOverhead();

  const branchOptions = (filterOptions?.branches ?? []).map((b) => ({
    value: String(b.id),
    label: b.name,
  }));

  const deptOptions = (filterOptions?.departments ?? []).map((d) => ({
    value: String(d.id),
    label: d.name,
  }));

  const machineOptions = (filterOptions?.machines ?? []).map((m) => ({
    value: String(m.assetId),
    label: m.name,
  }));

  const applyDatePreset = (preset: "this-month" | "last-month" | "ytd") => {
    const range = getPresetRange(preset);
    setPendingFilters((prev) => ({ ...prev, ...range }));
    setFilters((prev) => ({ ...prev, ...range }));
    setDetailsPage(1);
  };

  const isPresetActive = (preset: "this-month" | "last-month" | "ytd") => {
    const range = getPresetRange(preset);
    return filters.dateFrom === range.dateFrom && filters.dateTo === range.dateTo;
  };

  const removeFilter = (key: "branchId" | "departmentId" | "assetId") => {
    setPendingFilters((prev) => ({ ...prev, [key]: "" }));
    setFilters((prev) => ({ ...prev, [key]: "" }));
    setDetailsPage(1);
  };

  return (
    <div className="flex flex-col space-y-5 max-w-[1400px] mx-auto w-full">
      {/* Module Header */}
      <div className="flex flex-col gap-1">
        <h1 className="text-lg font-bold text-foreground flex items-center gap-2">
          <Settings2 className="h-5 w-5 text-primary shrink-0" />
          Machine Depreciation Overhead Allocation
        </h1>
        <p className="text-xs text-muted-foreground max-w-2xl">
          Reports actual depreciation generated by manufacturing equipment and its attribution to job orders based on
          production output, with visibility into UOP rates, capacity consumption, and attribution differences.
        </p>
      </div>

      {/* Global Filter Bar */}
      <div className="sticky top-0 z-20 rounded-xl border border-border/60 bg-background/95 backdrop-blur-md p-3.5 shadow-xs transition-shadow">
        {/* Date presets row */}
        <div className="flex flex-wrap items-center gap-2 mb-3 pb-2.5 border-b border-border/40">
          <span className="text-[11px] font-semibold text-muted-foreground flex items-center gap-1">
            <Calendar className="h-3 w-3" />
            Date Presets:
          </span>
          <button
            type="button"
            onClick={() => applyDatePreset("this-month")}
            className={`px-2.5 py-1 text-[11px] font-medium rounded-md border transition-colors cursor-pointer ${
              isPresetActive("this-month")
                ? "bg-primary text-primary-foreground border-primary font-semibold shadow-xs"
                : "border-input bg-background/80 hover:bg-muted text-muted-foreground hover:text-foreground"
            }`}
          >
            This Month
          </button>
          <button
            type="button"
            onClick={() => applyDatePreset("last-month")}
            className={`px-2.5 py-1 text-[11px] font-medium rounded-md border transition-colors cursor-pointer ${
              isPresetActive("last-month")
                ? "bg-primary text-primary-foreground border-primary font-semibold shadow-xs"
                : "border-input bg-background/80 hover:bg-muted text-muted-foreground hover:text-foreground"
            }`}
          >
            Last Month
          </button>
          <button
            type="button"
            onClick={() => applyDatePreset("ytd")}
            className={`px-2.5 py-1 text-[11px] font-medium rounded-md border transition-colors cursor-pointer ${
              isPresetActive("ytd")
                ? "bg-primary text-primary-foreground border-primary font-semibold shadow-xs"
                : "border-input bg-background/80 hover:bg-muted text-muted-foreground hover:text-foreground"
            }`}
          >
            YTD
          </button>
        </div>

        {/* Inputs row */}
        <div className="flex flex-wrap gap-3 items-end">
          {/* Date From */}
          <div className="flex flex-col gap-1 min-w-[130px]">
            <label className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wide">Date From</label>
            <input
              type="date"
              value={pendingFilters.dateFrom}
              onChange={(e) =>
                setPendingFilters((prev) => ({ ...prev, dateFrom: e.target.value }))
              }
              className="h-9 px-3 text-xs rounded-md border border-input bg-background focus:outline-none focus:ring-1 focus:ring-ring"
            />
          </div>

          {/* Date To */}
          <div className="flex flex-col gap-1 min-w-[130px]">
            <label className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wide">Date To</label>
            <input
              type="date"
              value={pendingFilters.dateTo}
              onChange={(e) =>
                setPendingFilters((prev) => ({ ...prev, dateTo: e.target.value }))
              }
              className="h-9 px-3 text-xs rounded-md border border-input bg-background focus:outline-none focus:ring-1 focus:ring-ring"
            />
          </div>

          {/* Branch */}
          <div className="flex flex-col gap-1 min-w-[160px]">
            <label className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wide">Branch</label>
            <SearchableSelect
              options={branchOptions}
              value={pendingFilters.branchId}
              onValueChange={(v) =>
                setPendingFilters((prev) => ({ ...prev, branchId: v === pendingFilters.branchId ? "" : v }))
              }
              placeholder="All Branches"
              searchPlaceholder="Search branch..."
              disabled={filterOptionsLoading}
            />
          </div>

          {/* Department */}
          <div className="flex flex-col gap-1 min-w-[160px]">
            <label className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wide">Department</label>
            <SearchableSelect
              options={deptOptions}
              value={pendingFilters.departmentId}
              onValueChange={(v) =>
                setPendingFilters((prev) => ({ ...prev, departmentId: v === pendingFilters.departmentId ? "" : v }))
              }
              placeholder="All Departments"
              searchPlaceholder="Search department..."
              disabled={filterOptionsLoading}
            />
          </div>

          {/* Machine */}
          <div className="flex flex-col gap-1 min-w-[180px]">
            <label className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wide">Machine</label>
            <SearchableSelect
              options={machineOptions}
              value={pendingFilters.assetId}
              onValueChange={(v) =>
                setPendingFilters((prev) => ({ ...prev, assetId: v === pendingFilters.assetId ? "" : v }))
              }
              placeholder="All Machines"
              searchPlaceholder="Search machine..."
              disabled={filterOptionsLoading}
            />
          </div>

          {/* Actions */}
          <div className="flex items-center gap-2 pb-0.5 ml-auto">
            <button
              type="button"
              onClick={resetFilters}
              className="flex items-center gap-1.5 h-9 px-3 text-xs rounded-md border border-input bg-background hover:bg-muted/50 cursor-pointer transition-colors"
            >
              <RotateCcw className="h-3 w-3" />
              Reset
            </button>
            <button
              type="button"
              onClick={applyFilters}
              className="flex items-center gap-1.5 h-9 px-3.5 text-xs rounded-md bg-primary text-primary-foreground hover:bg-primary/90 font-semibold cursor-pointer transition-colors shadow-xs"
            >
              Apply Filters
            </button>
          </div>
        </div>

        {/* Active filter chips */}
        {(filters.branchId || filters.departmentId || filters.assetId) && (
          <div className="flex flex-wrap items-center gap-2 mt-3 pt-2.5 border-t border-border/50">
            <span className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wide">
              Active Filters:
            </span>
            {filters.branchId && (
              <span className="inline-flex items-center gap-1.5 text-xs px-2.5 py-0.5 rounded-full bg-primary/10 text-primary border border-primary/20 font-medium">
                Branch: {branchOptions.find((b) => b.value === filters.branchId)?.label ?? filters.branchId}
                <button
                  type="button"
                  onClick={() => removeFilter("branchId")}
                  aria-label="Remove branch filter"
                  className="hover:text-destructive hover:bg-primary/20 rounded-full p-0.5 transition-colors cursor-pointer"
                >
                  <X className="h-3 w-3" />
                </button>
              </span>
            )}
            {filters.departmentId && (
              <span className="inline-flex items-center gap-1.5 text-xs px-2.5 py-0.5 rounded-full bg-primary/10 text-primary border border-primary/20 font-medium">
                Dept: {deptOptions.find((d) => d.value === filters.departmentId)?.label ?? filters.departmentId}
                <button
                  type="button"
                  onClick={() => removeFilter("departmentId")}
                  aria-label="Remove department filter"
                  className="hover:text-destructive hover:bg-primary/20 rounded-full p-0.5 transition-colors cursor-pointer"
                >
                  <X className="h-3 w-3" />
                </button>
              </span>
            )}
            {filters.assetId && (
              <span className="inline-flex items-center gap-1.5 text-xs px-2.5 py-0.5 rounded-full bg-primary/10 text-primary border border-primary/20 font-medium">
                Machine: {machineOptions.find((m) => m.value === filters.assetId)?.label ?? filters.assetId}
                <button
                  type="button"
                  onClick={() => removeFilter("assetId")}
                  aria-label="Remove machine filter"
                  className="hover:text-destructive hover:bg-primary/20 rounded-full p-0.5 transition-colors cursor-pointer"
                >
                  <X className="h-3 w-3" />
                </button>
              </span>
            )}
            <button
              type="button"
              onClick={resetFilters}
              className="text-[11px] text-muted-foreground hover:text-destructive underline ml-1 cursor-pointer transition-colors"
            >
              Clear all
            </button>
          </div>
        )}
      </div>

      {/* Tab Navigation */}
      <div className="flex border-b border-border/60 gap-1 bg-muted/10 px-1 pt-1 shrink-0">
        {TABS.map((tab) => (
          <button
            key={tab.id}
            type="button"
            onClick={() => setActiveTab(tab.id)}
            className={`px-4 py-2 text-xs font-semibold border-b-2 transition-all -mb-[1px] cursor-pointer rounded-t-md focus:outline-none focus-visible:ring-2 focus-visible:ring-ring ${
              activeTab === tab.id
                ? "border-primary text-primary bg-background shadow-xs font-bold"
                : "border-transparent text-muted-foreground hover:text-foreground hover:bg-muted/30"
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Tab Content with AnimatePresence */}
      <AnimatePresence mode="wait">
        <motion.div
          key={activeTab}
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -8 }}
          transition={{ duration: 0.22 }}
        >
          {activeTab === "overview" && (
            <OverviewTab
              data={overviewData}
              loading={overviewLoading}
              error={overviewError}
              onRefetch={refetchOverview}
            />
          )}
          {activeTab === "machines" && (
            <MachineAnalysisTab
              data={machinesData}
              loading={machinesLoading}
              error={machinesError}
              onRefetch={refetchMachines}
            />
          )}
          {activeTab === "job-orders" && (
            <JobOrderAllocationTab
              data={jobOrdersData}
              loading={jobOrdersLoading}
              error={jobOrdersError}
              onRefetch={refetchJobOrders}
            />
          )}
          {activeTab === "details" && (
            <DetailsTab
              data={detailsData}
              loading={detailsLoading}
              error={detailsError}
              page={detailsPage}
              onPageChange={setDetailsPage}
              onRefetch={refetchDetails}
            />
          )}
        </motion.div>
      </AnimatePresence>
    </div>
  );
}
