import { z } from "zod";
import type { RFIDTag, StockConversionProduct, StockConversionPayload } from "./stock-conversion.types";

export const rfidTagSchema = z.object({
  id: z.string().optional(),
  rfid_tag: z.string().min(1, "RFID tag is required"),
  status: z.enum(["active", "inactive"]).default("active"),
  assignedDate: z.string().optional(),
}) satisfies z.ZodType<RFIDTag>;

export const stockConversionProductSchema = z.object({
  productId: z.number(),
  supplierId: z.number().optional(),
  supplierName: z.string().optional(),
  supplierShortcut: z.string().optional(),
  brand: z.string(),
  category: z.string(),
  productCode: z.string(),
  productName: z.string(),
  productDescription: z.string(),
  family: z.string().optional(),
  conversionFactor: z.number().optional(),
  currentUnit: z.string(),
  currentUnitId: z.number(),
  quantity: z.number(),
  totalAmount: z.number(),
  pricePerUnit: z.number(),
  inventoryLoaded: z.boolean().optional(),
  inventoryError: z.boolean().optional(),
  availableUnits: z.array(z.object({
    unitId: z.number(),
    name: z.string(),
    conversionFactor: z.number().optional(),
    targetProductId: z.number().optional(),
  })).optional(),
}) satisfies z.ZodType<StockConversionProduct>;

export const stockConversionPayloadSchema = z.object({
  productId: z.number(),
  sourceUnitId: z.number(),
  targetUnitId: z.number(),
  targetProductId: z.number(),
  quantityToConvert: z.number().gt(0, "Quantity must be greater than 0"),
  convertedQuantity: z.number().gt(0, "Converted quantity must be greater than 0"),
  branchId: z.number().min(1, "Branch ID is required"),
  userId: z.number().min(1, "User ID is required"),
  pricePerUnit: z.number(),
  rfidTags: z.array(rfidTagSchema).default([]),
  sourceRfidTags: z.array(z.string()).optional(),
  sourceFactor: z.number().optional(),
  targetFactor: z.number().optional(),
  // Lot & Batch Tracking
  sourceInventoryLotId: z.number().optional(),
  sourceLotId: z.number().optional(),
  sourceLotName: z.string().optional(),
  sourceBatchNo: z.string().optional(),
  sourceManufacturingDate: z.string().nullable().optional(),
  sourceExpiryDate: z.string().nullable().optional(),
  sourceAllocations: z.array(z.object({
    inventory_lot_id: z.number().optional(),
    lot_id: z.number().optional(),
    batch_no: z.string().optional(),
    allocated_quantity: z.number().optional(),
    manufacturing_date: z.string().nullable().optional(),
    expiry_date: z.string().nullable().optional(),
    qa_status: z.string().optional(),
    unit_cost: z.number().optional(),
  })).optional(),
  targetLotId: z.number().optional(),
  targetLotName: z.string().optional(),
  targetBatchNo: z.string().optional(),
  targetManufacturingDate: z.string().nullable().optional(),
  targetExpiryDate: z.string().nullable().optional(),
  targetQaStatus: z.enum(["GOOD", "DAMAGED", "QUARANTINED", "EXPIRED"]).optional(),
  targetAllocations: z.array(z.object({
    lot_id: z.number(),
    lot_name: z.string(),
    max_batch_capacity: z.number(),
    unit_id: z.number().nullable().optional(),
    unit_name: z.string().nullable().optional(),
    allocated_quantity: z.number(),
    active_batch_count: z.number().optional(),
    current_stock_quantity: z.number().optional(),
    batches: z.array(z.object({
      inventory_lot_id: z.number().optional(),
      batch_no: z.string(),
      manufacturing_date: z.string().nullable().optional(),
      expiry_date: z.string().nullable().optional(),
      quantity: z.number(),
      unit_cost: z.number().optional(),
      qa_status: z.enum(["GOOD", "DAMAGED", "QUARANTINED", "EXPIRED"]),
      is_existing: z.boolean().optional(),
    })),
  })).optional(),
}) satisfies z.ZodType<StockConversionPayload>;
