import type { jsPDF } from "jspdf";
import type { PurchaseOrderPrintableSnapshot } from "./types";

type PdfDocument = InstanceType<typeof jsPDF>;

function money(value: number, currency: string): string {
    return new Intl.NumberFormat("en-PH", {
        style: "currency",
        currency: currency || "PHP",
        maximumFractionDigits: 2
    }).format(Number.isFinite(value) ? value : 0);
}

function quantity(value: number): string {
    return new Intl.NumberFormat("en-PH", { maximumFractionDigits: 4 }).format(Number.isFinite(value) ? value : 0);
}

function displayDate(value: string): string {
    if (!value || value === "N/A") return "N/A";
    const date = new Date(value);
    return Number.isNaN(date.getTime()) ? value : date.toLocaleString("en-PH");
}

function pdfText(value: unknown, fallback = "N/A"): string {
    const result = String(value ?? "").trim();
    return result || fallback;
}

function currentY(doc: PdfDocument, fallback: number): number {
    const lastTable = (doc as PdfDocument & { lastAutoTable?: { finalY?: number } }).lastAutoTable;
    return lastTable?.finalY ? lastTable.finalY + 7 : fallback;
}

function drawHeader(doc: PdfDocument, data: PurchaseOrderPrintableSnapshot, title: string): number {
    const pageWidth = doc.internal.pageSize.getWidth();
    const company = data.company;
    if (company.logoDataUrl) {
        try {
            const format = company.logoDataUrl.startsWith("data:image/jpeg") || company.logoDataUrl.startsWith("data:image/jpg") ? "JPEG" : "PNG";
            doc.addImage(company.logoDataUrl, format, 10, 8, 20, 20);
        } catch {
            // A missing or unsupported logo must not prevent the compliance document from rendering.
        }
    }
    const left = company.logoDataUrl ? 34 : 10;
    doc.setFont("helvetica", "bold").setFontSize(12);
    doc.text(pdfText(company.name, "Vertex Manufacturing"), left, 14);
    doc.setFont("helvetica", "normal").setFontSize(7);
    const addressLines = doc.splitTextToSize(pdfText(company.address), 90) as string[];
    doc.text(addressLines.slice(0, 2), left, 19);
    doc.text(`Contact: ${pdfText(company.contact)} | ${pdfText(company.email)}`, left, 28);

    doc.setFont("helvetica", "bold").setFontSize(11);
    doc.text(title, pageWidth - 10, 14, { align: "right" });
    doc.setFont("helvetica", "normal").setFontSize(7);
    doc.text(`PO: ${pdfText(data.purchaseOrder.purchaseOrderNumber)}`, pageWidth - 10, 19, { align: "right" });
    doc.text(`Generated: ${displayDate(data.generatedAt)}`, pageWidth - 10, 24, { align: "right" });
    doc.text(`Generated by: ${pdfText(data.generatedBy)}`, pageWidth - 10, 29, { align: "right" });
    doc.setDrawColor(70, 70, 70).line(10, 34, pageWidth - 10, 34);
    return 42;
}

function drawSectionTitle(doc: PdfDocument, title: string, y: number): number {
    doc.setFont("helvetica", "bold").setFontSize(9).setTextColor(30, 30, 30);
    doc.text(title, 10, y);
    doc.setTextColor(0, 0, 0);
    return y + 5;
}

function drawFooter(doc: PdfDocument, data: PurchaseOrderPrintableSnapshot): void {
    const pageCount = doc.getNumberOfPages();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    for (let page = 1; page <= pageCount; page += 1) {
        doc.setPage(page);
        doc.setDrawColor(170, 170, 170).line(10, pageHeight - 14, pageWidth - 10, pageHeight - 14);
        doc.setFont("helvetica", "normal").setFontSize(6).setTextColor(90, 90, 90);
        doc.text("System-generated manufacturing purchase-order compliance document", 10, pageHeight - 9);
        doc.text(`Template: ${pdfText(data.template.name)} v${pdfText(data.template.version)}`, pageWidth / 2, pageHeight - 9, { align: "center" });
        doc.text(`Page ${page} of ${pageCount}`, pageWidth - 10, pageHeight - 9, { align: "right" });
        doc.setTextColor(0, 0, 0);
    }
}

async function renderTable(
    doc: PdfDocument,
    startY: number,
    head: string[],
    body: string[][],
    orientation: "portrait" | "landscape" = "portrait"
): Promise<number> {
    const autoTableModule = await import("jspdf-autotable");
    const autoTable = (autoTableModule.default || autoTableModule) as typeof import("jspdf-autotable").default;
    autoTable(doc, {
        startY,
        head: [head],
        body,
        theme: "grid",
        styles: { font: "helvetica", fontSize: orientation === "landscape" ? 7 : 7.5, cellPadding: 2, overflow: "linebreak" },
        headStyles: { fillColor: [31, 78, 121], textColor: [255, 255, 255], fontStyle: "bold" },
        alternateRowStyles: { fillColor: [245, 248, 251] },
        margin: { left: 10, right: 10, bottom: 20 },
        tableWidth: "auto"
    });
    return currentY(doc, startY + 12);
}

async function renderPoDocument(doc: PdfDocument, data: PurchaseOrderPrintableSnapshot, y: number): Promise<number> {
    const po = data.purchaseOrder;
    y = drawSectionTitle(doc, "Purchase-order details", y);
    y = await renderTable(doc, y, ["PO number", "Reference", "Encoded date", "Price type"], [[
        po.purchaseOrderNumber,
        po.reference,
        displayDate(po.encodedAt),
        po.priceType
    ]]);
    y = await renderTable(doc, y, ["Supplier", "Destination branch", "Payment terms", "Payment mode", "Currency", "Status"], [[
        `${po.supplier}\n${po.supplierAddress}`,
        po.branch,
        po.paymentTerms,
        `${po.paymentMode}\n${po.paymentArrangement}`,
        `${po.currencyCode} @ ${po.exchangeRate.toFixed(4)}`,
        `${po.inventoryStatus}\n${po.paymentStatus}`
    ]]);
    if (po.isForceReceived) {
        y = drawSectionTitle(doc, "Force Received", y);
        y = await renderTable(doc, y, ["Closed at", "Force Close Reason"], [[
            po.forceReceivedAt || "N/A",
            po.forceReceivedReason || "N/A"
        ]]);
    }
    y = drawSectionTitle(doc, "Purchase-order lines", y);
    y = await renderTable(doc, y,
        ["Product", "Category", "UOM", "Ordered", "Received", "Accepted", "Rejected", "Unit price", "Net amount"],
        data.lines.map(line => [
            `${line.productName}\n${line.productCode}`,
            line.categoryType,
            line.unit,
            quantity(line.orderedQuantity),
            quantity(line.receivedQuantity),
            quantity(line.acceptedQuantity),
            quantity(line.rejectedQuantity),
            money(line.unitPriceForeign, po.currencyCode),
            money(line.netAmount, po.currencyCode)
        ]));
    y = drawSectionTitle(doc, "Financial summary", y);
    y = await renderTable(doc, y, ["Gross amount", "Total amount", "Foreign amount", "Workflow revision", "Posted", "Amounts posted"], [[
        money(po.grossAmount, "PHP"),
        money(po.totalAmount, "PHP"),
        money(po.totalForeignCurrency, po.currencyCode),
        String(po.workflowRevision),
        po.isPosted ? "Yes" : "No",
        po.isPostedAmounts ? "Yes" : "No"
    ]]);
    if (po.remark) {
        y = drawSectionTitle(doc, "Purchase notes and special terms", y + 2);
        doc.setFont("helvetica", "normal").setFontSize(8);
        const remarkLines = doc.splitTextToSize(po.remark, doc.internal.pageSize.getWidth() - 20) as string[];
        doc.text(remarkLines, 10, y);
        y += remarkLines.length * 4;
    }
    return y;
}

async function renderFinanceDocument(doc: PdfDocument, data: PurchaseOrderPrintableSnapshot, y: number): Promise<number> {
    const selected = data.selectedApproval;
    y = drawSectionTitle(doc, "Finance decision", y);
    y = await renderTable(doc, y, ["Decision", "Stage", "Actor", "Decision date", "Status transition", "Revision"], [[
        selected?.action || "N/A",
        selected?.stage || "N/A",
        `${selected?.actor || "N/A"}\nRole: ${selected?.actorRole || "N/A"}`,
        selected ? displayDate(selected.createdAt) : "N/A",
        selected ? `${selected.fromStatus} -> ${selected.toStatus}` : "N/A",
        selected ? `${selected.revisionBefore} -> ${selected.revisionAfter}` : "N/A"
    ]]);
    if (selected?.remarks) {
        y = drawSectionTitle(doc, "Finance remarks", y + 2);
        doc.setFont("helvetica", "normal").setFontSize(8);
        doc.text(doc.splitTextToSize(selected.remarks, doc.internal.pageSize.getWidth() - 20), 10, y);
        y += 12;
    }
    y = drawSectionTitle(doc, "Purchase-order snapshot", y + 4);
    y = await renderTable(doc, y, ["Product", "Ordered", "Unit price", "Discount", "Net amount"], data.lines.map(line => [
        `${line.productName}\n${line.productCode}`,
        quantity(line.orderedQuantity),
        money(line.unitPriceForeign, data.purchaseOrder.currencyCode),
        money(line.discountAmount, data.purchaseOrder.currencyCode),
        money(line.netAmount, data.purchaseOrder.currencyCode)
    ]));
    y = drawSectionTitle(doc, "Approval history", y);
    y = await renderTable(doc, y, ["Action", "Stage", "Actor", "Remarks", "Created", "Revision"], data.approvals.map(entry => [
        entry.action,
        entry.stage,
        entry.actor,
        entry.remarks || "N/A",
        displayDate(entry.createdAt),
        `${entry.revisionBefore} -> ${entry.revisionAfter}`
    ]));
    return y;
}

async function renderQaDocument(doc: PdfDocument, data: PurchaseOrderPrintableSnapshot, y: number): Promise<number> {
    const po = data.purchaseOrder;
    y = drawSectionTitle(doc, "Goods-receipt handoff", y);
    y = await renderTable(doc, y, ["PO", "Receipt header", "Receipt count", "Status", "Payment status", "Workflow revision"], [[
        po.purchaseOrderNumber,
        data.sourceReceivingHeaderId ? `#${data.sourceReceivingHeaderId}` : "All committed receipts",
        String(data.receivingRecords.length),
        po.inventoryStatus,
        po.paymentStatus,
        String(po.workflowRevision)
    ]]);
    y = drawSectionTitle(doc, "QA inspection and receiving records", y);
    y = await renderTable(doc, y,
        ["Product", "Receipt / batch", "Branch / lot", "Received", "Accepted", "Rejected", "Over-delivery", "QA", "Expiry"],
        data.receivingRecords.map(record => [
            `${record.product}\n${record.productCode}`,
            `${record.receiptNumber}\n${record.batchNumber}`,
            `${record.branch}\n${record.storageLot}`,
            quantity(record.receivedQuantity),
            quantity(record.acceptedQuantity),
            quantity(record.rejectedQuantity),
            quantity(record.overDeliveryQuantity),
            record.qaStatus,
            record.expirationDate
        ]));
    return y;
}

async function renderStorageDocument(doc: PdfDocument, data: PurchaseOrderPrintableSnapshot, y: number): Promise<number> {
    y = drawSectionTitle(doc, "Inventory movement and storage-lot handoff", y);
    y = await renderTable(doc, y,
        ["Kind", "Product", "Storage lot", "Branch", "Quantity", "Transaction", "Source / batch"],
        data.movements.map(movement => [
            movement.kind,
            `${movement.product}\n${movement.productCode}`,
            movement.storageLot,
            movement.branch,
            quantity(movement.quantity),
            movement.transactionType,
            `${movement.sourceDocument}\n${movement.batchNumber}`
        ]));
    y = drawSectionTitle(doc, "MRP storage allocations", y);
    y = await renderTable(doc, y, ["Allocation", "Product", "Job order", "Material", "Quantity", "Inventory lots"], data.allocations.map(allocation => [
        String(allocation.allocationId),
        allocation.product,
        allocation.jobOrder,
        allocation.material,
        quantity(allocation.quantity),
        allocation.inventoryLots
    ]));
    return y;
}

async function renderLandedCostDocument(doc: PdfDocument, data: PurchaseOrderPrintableSnapshot, y: number): Promise<number> {
    const landedCost = data.landedCost;
    if (!landedCost) return y;
    y = drawSectionTitle(doc, "Landed-cost computation", y);
    y = await renderTable(doc, y, ["Computation", "Status", "Allocation rule", "Total landed fee", "Rounding variance", "Finalized"], [[
        `#${landedCost.computationId}`,
        landedCost.status,
        landedCost.allocationRule,
        money(landedCost.totalLandedFee, "PHP"),
        money(landedCost.roundingVariance, "PHP"),
        displayDate(landedCost.finalizedAt)
    ]]);
    if (landedCost.expenses.length > 0) {
        y = drawSectionTitle(doc, "Landed-cost expenses", y);
        y = await renderTable(doc, y, ["Expense", "Chart of account", "Amount"], landedCost.expenses.map(expense => [
            expense.expenseType,
            expense.account,
            money(expense.amount, "PHP")
        ]));
    }
    y = drawSectionTitle(doc, "Line allocation", y);
    y = await renderTable(doc, y, ["Product", "Quantity", "Base unit cost", "Allocated fee", "Final landed unit cost", "Share"], landedCost.allocations.map(allocation => [
        allocation.product,
        quantity(allocation.quantity),
        money(allocation.baseUnitCost, "PHP"),
        money(allocation.allocatedExpense, "PHP"),
        money(allocation.finalLandedUnitCost, "PHP"),
        allocation.allocationPercent == null ? "N/A" : `${allocation.allocationPercent.toFixed(4)}%`
    ]));
    if (landedCost.attachments.length > 0) {
        y = drawSectionTitle(doc, "Supporting computation files", y);
        doc.setFont("helvetica", "normal").setFontSize(8);
        const attachmentLines = doc.splitTextToSize(landedCost.attachments.join("\n"), doc.internal.pageSize.getWidth() - 20) as string[];
        doc.text(attachmentLines, 10, y);
        y += attachmentLines.length * 4;
    }
    return y;
}

async function renderAuditBlock(doc: PdfDocument, data: PurchaseOrderPrintableSnapshot, y: number): Promise<number> {
    const selectedApproval = data.selectedApproval;
    y = drawSectionTitle(doc, "Audit source records and sign-off", y + 3);
    return renderTable(doc, y, ["Audit field", "Value", "Audit field", "Value"], [
        ["Document type", data.documentType, "Purchase-order ID", String(data.purchaseOrder.id)],
        ["Workflow revision", String(data.purchaseOrder.workflowRevision), "Template", `${data.template.name} v${data.template.version}`],
        ["Approval history ID", selectedApproval ? String(selectedApproval.historyId) : "N/A", "Receiving header ID", data.sourceReceivingHeaderId ? String(data.sourceReceivingHeaderId) : "N/A"],
        ["Landed-cost computation ID", data.landedCost ? String(data.landedCost.computationId) : "N/A", "Generated by", data.generatedBy],
        ["Generated at", displayDate(data.generatedAt), "PO source", `purchase_order:${data.purchaseOrder.id}`],
        ["Buyer / preparer sign-off", "Signature/date: ____________________", "Finance / QA sign-off", "Signature/date: ____________________"]
    ]);
}

export async function generatePurchaseOrderPdf(data: PurchaseOrderPrintableSnapshot): Promise<{ buffer: Buffer; pageCount: number }> {
    const jsPDFModule = await import("jspdf");
    const JsPDFClass = (jsPDFModule.default || jsPDFModule.jsPDF) as unknown as typeof import("jspdf").jsPDF;
    const doc = new JsPDFClass({ orientation: "portrait", unit: "mm", format: "a4" });
    const titles: Record<PurchaseOrderPrintableSnapshot["documentType"], string> = {
        PURCHASE_ORDER: "PURCHASE ORDER",
        FINANCE_DECISION: "FINANCE DECISION",
        QA_GOODS_RECEIPT: "QA GOODS RECEIPT",
        STORAGE_LOT_ALLOCATION: "STORAGE-LOT ALLOCATION",
        LANDED_COST: "LANDED-COST COMPUTATION"
    };
    const y = drawHeader(doc, data, titles[data.documentType]);
    let contentY = y;
    switch (data.documentType) {
        case "PURCHASE_ORDER": contentY = await renderPoDocument(doc, data, y); break;
        case "FINANCE_DECISION": contentY = await renderFinanceDocument(doc, data, y); break;
        case "QA_GOODS_RECEIPT": contentY = await renderQaDocument(doc, data, y); break;
        case "STORAGE_LOT_ALLOCATION": contentY = await renderStorageDocument(doc, data, y); break;
        case "LANDED_COST": contentY = await renderLandedCostDocument(doc, data, y); break;
    }
    await renderAuditBlock(doc, data, Math.max(contentY, currentY(doc, y)));
    drawFooter(doc, data);
    return { buffer: Buffer.from(doc.output("arraybuffer")), pageCount: doc.getNumberOfPages() };
}
